# Generated by Django 4.2.7 on 2023-11-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(default=0)),
                ('is_option', models.BooleanField(default=True)),
                ('product_date', models.DateField(auto_now_add=True)),
                ('product_thumnail', models.ImageField(upload_to='product_thumnails/')),
                ('product_description', models.TextField(verbose_name=1000)),
                ('is_display', models.BooleanField(default=True)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('sales_volume', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_point', models.IntegerField(default=0)),
                ('is_email', models.BooleanField(default=True)),
                ('sub_date', models.DateField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.product')),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(related_name='product_images', to='main.productimage'),
        ),
        migrations.CreateModel(
            name='OptionList',
            fields=[
                ('option_no', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=20)),
                ('option_value', models.CharField(max_length=20)),
                ('option_amount', models.IntegerField(default=0)),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.product')),
            ],
        ),
    ]
