# Generated by Django 4.2.7 on 2023-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='refund_bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
