# Generated by Django 4.2.7 on 2023-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_optionlist_option_stock_product_total_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionlist',
            name='option_name_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option_value_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
