# Generated by Django 4.2.7 on 2023-12-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_birth_date_customuser_gender_and_more'),
        ('main', '0003_optionlist_option_name_add_and_more'),
    ]

    operations = [
    ]
