# Generated by Django 4.2.7 on 2023-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20231207_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
