# Generated by Django 4.2.7 on 2023-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_no", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=20)),
                ("admin_email", models.CharField(max_length=100)),
                ("admin_password", models.CharField(max_length=100)),
                ("admin_phone", models.CharField(max_length=11)),
                ("admin_grade", models.IntegerField(default=1)),
                ("created_date", models.DateTimeField(default=0)),
            ],
        ),
    ]
